In [28]:
from MCCA import MCCA
import pandas as pd
import numpy as np 
import os
os.chdir(r'C:/Users/Mansi/Downloads/')
os.getcwd()
X1=pd.read_csv('mfeat-fac', delim_whitespace=True,header=None)
X2=pd.read_csv('mfeat-zer', delim_whitespace=True,header=None)
X3=pd.read_csv('mfeat-kar', delim_whitespace=True,header=None)

In [29]:
print(X1.shape,X2.shape,X3.shape)

(2000, 216) (2000, 47) (2000, 64)

In [30]:
X1.head()

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,98,236,531,673,607,647,2,9,3,6,...,474,536,628,632,18,36,8,15,12,13
1,121,193,607,611,585,665,7,9,2,4,...,520,458,570,634,15,32,11,13,15,11
2,115,141,590,605,557,627,12,6,3,3,...,535,498,572,656,20,35,16,14,13,6
3,90,122,627,692,607,642,0,6,4,5,...,576,549,628,621,16,35,7,12,15,9
4,157,167,681,666,587,666,8,6,1,4,...,594,525,568,653,16,35,10,15,13,13

In [25]:
X_list =[X1,X2,X3]
mcca = MCCA(n_components=3,reg_param=0.001)
mcca.fit([X1,X2,X3])
X_reduced = mcca.transform([X1,X2,X3])
for i in range(len(X_reduced)):
    print("X_reduced_{0}->{1}\n".format(i+1,X_reduced[i]))

X_reduced_1->[[-6.2043648  -8.21000167 -8.70828247]
 [-6.04422431 -7.12721066 -7.33889951]
 [-9.20500896 -9.94272409 -9.99668279]
 ...
 [-2.45007725 -0.10051748  1.06471701]
 [-4.34640264 -2.42383934 -1.21784254]
 [ 5.76130801  7.80608203  8.53718085]]

X_reduced_2->[[-4.78326414 -5.44646409 -5.66947341]
 [-4.38513039 -4.60472924 -4.68805835]
 [-5.40037379 -5.64120969 -5.80726838]
 ...
 [-3.55641485 -3.25777344 -3.10820102]
 [-4.92470045 -4.94798254 -4.76726507]
 [-1.80022906 -1.21047425 -1.01528449]]

X_reduced_3->[[-0.52886199 -1.09916744 -1.29483348]
 [-1.06434809 -1.7547311  -2.0939277 ]
 [-0.73112763 -0.62419567 -0.54825171]
 ...
 [-2.0483634  -0.9282443  -0.26526669]
 [-1.47795114 -1.1712895  -0.93259372]
 [ 0.54554381  1.32189003  1.71488153]]

C:\Users\MANSI\Desktop\MCCA.py:90: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  weights[i] = np.hstack(x.reshape(dimen[i],1) for x in weights[i])

In [26]:
X_list =[X1,X2,X3]
m = MCCA(n_components=6,reg_param=0.001)
m.fit([X1,X2,X3])
X_reduced = m.transform([X1,X2,X3])
for i in range(len(X_reduced)):
    print("X_reduced_{0}->{1}\n".format(i+1,X_reduced[i]))

X_reduced_1->[[-6.56402216 -8.25962714 -8.68393839 -8.82681662 -8.88571157 -8.91482796]
 [-5.7694711  -6.83912119 -7.11781503 -7.18638836 -7.19804577 -7.19641214]
 [-9.12961234 -9.66819736 -9.7603724  -9.75259597 -9.72892483 -9.70923719]
 ...
 [-0.43829421  1.06640933  1.75122633  2.09885466  2.2897784   2.39886676]
 [-2.20469753 -0.99442378 -0.3218331   0.06811055  0.30219678  0.44444957]
 [ 7.10909159  8.43230644  8.84278621  9.00473821  9.07373288  9.10349242]]

X_reduced_2->[[-4.83607829 -5.51822704 -5.71435789 -5.78108682 -5.80978069 -5.82477699]
 [-4.38117175 -4.62696375 -4.70271136 -4.73199611 -4.74443845 -4.75009807]
 [-5.61180744 -5.81808601 -5.9214144  -5.98195206 -6.01847227 -6.04099957]
 ...
 [-3.27373763 -3.11021579 -3.02403377 -2.9791467  -2.95141004 -2.93307269]
 [-4.52530124 -4.62330889 -4.54051982 -4.45916585 -4.39581506 -4.34984319]
 [-1.50363653 -1.04709846 -0.92827972 -0.88621445 -0.86356408 -0.84857105]]

X_reduced_3->[[-0.62390623 -1.13834246 -1.31002717 -1.37689721 -1.40763694 -1.42385272]
 [-1.07006047 -1.82098263 -2.12124596 -2.23598441 -2.28161427 -2.30109907]
 [-0.67007353 -0.53751146 -0.48752755 -0.47259198 -0.47053028 -0.47294912]
 ...
 [-1.06875537 -0.32376935  0.09991278  0.31721506  0.42981846  0.48982994]
 [-1.06743916 -0.85825507 -0.72857601 -0.65068211 -0.60427711 -0.5767215 ]
 [ 1.0658062   1.66725721  1.90277737  2.00292236  2.05140949  2.07682579]]

C:\Users\MANSI\Desktop\MCCA.py:90: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  weights[i] = np.hstack(x.reshape(dimen[i],1) for x in weights[i])